import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import QueryProvider from '../components/provider/QueryProvider';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div className="bg-white">
            <Link href="/" className="text-black text-xl font-bold">
              Home
            </Link>
          </div>
        </nav>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
